email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Michael Descy"
tagline: ""
description: "Follow <a href=\"https://micro.blog/mjdescy\">@mjdescy on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/mjdescy\">@mjdescy on Micro.blog</a>."
baseurl: ""
url: "https://micro.mjdescy.me"
markdown: "kramdown"
username: "mjdescy"
microblog_user: "mjdescy"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Michael Descy"
name: "Michael Descy"
gravatar_hash: "15e0360269ca80f49dda5e1c6169226a"
avatar: "https://micro.blog/mjdescy/avatar.jpg"
full_name: "Michael Descy"
bio: ""
twitter_username: "mjdescy"
github_username: "mjdescy"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "2098"
gems: ["jekyll-paginate"]
itunes_description: "Iâ€™m an auditor who also programs (Swift, C#, ObjC, VBA) does data work (ACL) and writes (blog @ mjdescy.me). I write and maintain the SwiftoDo apps, which are todo.txt task list apps for iOS and macOS."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Michael Descy"
itunes_email: ""
podcast: false